
- name: Setup localhost
  hosts: localhost
  vars_prompt:
  - name: ansible_become_password
    prompt: "Enter sudo password"
    private: true
  become: false

  tasks:
  - name: Update DNF cache
    dnf:
      update_cache: yes
    become: true

  - name: Install required packages
    dnf:
      name: "{{ item }}"
      state: present
    loop:
      - firefox
      - vim
      - curl
      - git
      - systemd-devel
      - "@Virtualization"
      - "@Development Tools"
    become: true

  - name: Install Rust
    shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    args:
      creates: /home/$USER/.cargo/bin/rustc

  - name: Create build directory
    file:
      path: ~/build
      state: directory

  - name: Clone supergfxctl repository
    git:
      repo: https://gitlab.com/asus-linux/supergfxctl.git
      dest: ~/build/supergfxctl

  - name: Source .bash_profile to refresh PATH and build supergfxctl
    shell: . ~/.bash_profile && make
    args:
      executable: /bin/bash
      chdir: ~/build/supergfxctl

  - name: Install supergfxctl
    command:
      cmd: make install
      chdir: "/home/{{ ansible_user }}/build/supergfxctl"
    become: true

  - name: Enable and start supergfxd service
    systemd:
      name: supergfxd
      state: started
      enabled: yes
    become: true

  - name: Copy supergfxd configuration file to remote
    copy:
      src: supergfxd.conf
      dest: /etc/supergfxd.conf
      backup: yes
      mode: '0644'
    become: true
    notify: restart supergfxd

  - name: Enable and start libvirtd service
    systemd:
      name: libvirtd
      state: started
      enabled: yes
    become: true
    notify: restart libvirtd
