# handlers/restart_services.yml

- name: restart supergfxd
  systemd:
    name: supergfxd
    state: restarted
    enabled: yes

- name: restart libvirtd
  systemd:
    name: libvirtd
    state: restarted
    enabled: yes