
- name: Setup localhost
  hosts: localhost
  become: false

  tasks:
  - name: Update DNF cache
    dnf:
      update_cache: yes
    become: true

  - name: Install required packages
    dnf:
      name: "{{ item }}"
      state: present
    loop:
      - firefox
      - vim
      - curl
      - git
      - "@Virtualization"
      - "@Development Tools"
    become: true

  - name: Install Rust
    shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    args:
      creates: /home/$USER/.cargo/bin/rustc

  - name: Create build directory
    file:
      path: ~/build
      state: directory

  - name: Clone supergfxctl repository
    git:
      repo: https://gitlab.com/asus-linux/supergfxctl.git
      dest: ~/build/supergfxctl

  - name: Source .bash_profile to refresh PATH
    shell: . ~/.bash_profile && make
    args:
      executable: /bin/bash
      chdir: ~/build/supergfxctl

  - name: Install supergfxctl
    command:
      cmd: make install
      chdir: ~/build/supergfxctl
    become: true

  - name: Enable and start supergfxd service
    systemd:
      name: supergfxd
      state: started
      enabled: yes
    become: true

  - name: Update supergfxd configuration
    lineinfile:
      path: /etc/supergfxd.conf
      line: "vfio_save: true"
      state: present
      backup: yes
      create: yes
      mode: '0644'
    become: true

  - name: Enable and start libvirtd service
    systemd:
      name: libvirtd
      state: started
      enabled: yes
    become: true

